version: '3.8'

services:
  frontend:
    build:
      context: ./front-end
      args:
        VITE_API_BASE_URL: http://yousaf.ddns.net/api
    expose:
      - "5173"
    networks:
      - chat-network
      - npm_network

  chat-service:
    build:
      context: "./chat-service"
    expose:
      - "5000"
    environment:
      - PORT=5000
      - ALLOWED_ORIGINS=http://yousaf.ddns.net
    depends_on:
      - mongo
    networks:
      - chat-network
      - npm_network

  mongo:
    image: mongo:6
    volumes:
      - mongo-data:/data/db
    networks:
      - chat-network
    hostname: mongo

  user-service:
    build:
      context: "./user-service"
    expose:
      - "5001"
    environment:
      - PORT=5001
      - ALLOWED_ORIGINS=http://yousaf.ddns.net
    depends_on:
      - mongo
    networks:
      - chat-network
      - npm_network

  auth-service:
    build:
      context: "./auth-service"
    expose:
      - "5002"
    environment:
      - PORT=5002
      - ALLOWED_ORIGINS=http://yousaf.ddns.net
    depends_on:
      - mongo
    networks:
      - chat-network
      - npm_network

volumes:
  mongo-data:

networks:
  chat-network:
  npm_network:
    external: true