version: '3.8'

services:
  frontend:
    build: 
      context: ./front-end
    ports:
      - "5173:5173"
    networks:
      - chat-network

  chat-service:
    build: 
      context: "./chat-service"
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - chat-network

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - chat-network
    hostname: "mongo"

  user-service:
    build: 
      context: "./user-service"
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    networks:
      - chat-network

  auth-service:
    build:
      context: "./auth-service"
    ports:
      - "5002:5002"
    depends_on:
      - mongo
    networks:
      - chat-network

volumes:
  mongo-data:

networks:
  chat-network:
