version: '3.8'

services:
  frontend:
    build: 
      context: ./front-end
    ports:
      - "5173:5173"

  chat-service:
    build: 
      context: "./chat-service"
    ports:
      - "5000:5000"

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
    - mongo-data:/data/db

volumes:
  mongo-data:
